### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by yrabbit** [grughuhler/picorv32#1]
Hello,
I'm making Gowin chip primitives for the https://github.com/YosysHQ/apicula project and I want to ask: would you mind if I used your fast Flash controller in the examples section for the UserFlash primitive?

Yes I have read the license, but I prefer to ask in person.

**Comment by grughuhler** [comment]
Feel free to use the controller.  Thanks for working on apicula.  I am hoping to look at it someday.
